name: Auto Merge PRs on Success

on:
  pull_request:
    types: [closed]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  automerge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
      - name: Auto-merge PR
        run: |
          gh pr merge ${{ github.event.workflow_run.pull_requests[0].number }} --merge --admin --delete-branch || echo "No PR to merge or already merged."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
